version: '3'
services:
  
  db:
    image: mysql:8.4
    container_name: db_kc
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloakpassword
    ports:
      - "3306:3306"
    networks:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  kc:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: kc
    environment:
      # Keycloak Configuration and Admin User
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      # Keycloak Configuration for monitoring
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      
      # Keycloak Configuration for Database
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloakpassword
      
      # Keycloak Configuration for HTTP
      - KC_HOSTNAME=http://localhost:8000/
      - KC_HTTP_ENABLED=true

    command: ['start']
    depends_on:
      db:
        condition: service_healthy
    networks:
      - private
      - db

  lb:
    image: nginx:latest
    container_name: lb
    ports:
      - "8000:80"
    networks:
      - public
      - private
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - kc

networks:
  db:
  private:
  public: